# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x0ewindows_events\"\x81\x01\n\x07Process\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\x11parent_process_id\x18\x02 \x01(\x05\x12\x12\n\nprocess_id\x18\x03 \x01(\x05\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\x12\x16\n\x0e\x61pplication_id\x18\x06 \x01(\x05\"\\\n\x0b\x41pplication\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\npe_file_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06vendor\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"h\n\x06PeFile\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06sha256\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x15\n\rmodified_time\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\"Q\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x13security_identifier\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\"\xb7\x01\n\x07Message\x12*\n\tprocesses\x18\x01 \x03(\x0b\x32\x17.windows_events.Process\x12\x31\n\x0c\x61pplications\x18\x02 \x03(\x0b\x32\x1b.windows_events.Application\x12(\n\x08pe_files\x18\x03 \x03(\x0b\x32\x16.windows_events.PeFile\x12#\n\x05users\x18\x04 \x03(\x0b\x32\x14.windows_events.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESS']._serialized_start=33
  _globals['_PROCESS']._serialized_end=162
  _globals['_APPLICATION']._serialized_start=164
  _globals['_APPLICATION']._serialized_end=256
  _globals['_PEFILE']._serialized_start=258
  _globals['_PEFILE']._serialized_end=362
  _globals['_USER']._serialized_start=364
  _globals['_USER']._serialized_end=445
  _globals['_MESSAGE']._serialized_start=448
  _globals['_MESSAGE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
